functional:
  female:
    age_stats:
      max: 63
      mean: 50.333333333333336
      min: 32
      std: 8.697531766169607
    total: 18
  male:
    age_stats:
      max: 65
      mean: 65
      min: 65
      std: null
    total: 1
muscle_tension:
  female:
    age_stats:
      max: 59
      mean: 36.5
      min: 21
      std: 11.575836902790225
    total: 16
normal:
  female:
    age_stats:
      max: 28
      mean: 21.533333333333335
      min: 20
      std: 2.1429163295565754
    total: 60
  male:
    age_stats:
      max: 26
      mean: 22.818181818181817
      min: 20
      std: 2.522624895547565
    total: 11
organic:
  female:
    age_stats:
      max: 69
      mean: 53.125
      min: 36
      std: 11.169514963333414
    total: 32
  male:
    age_stats:
      max: 78
      mean: 59.07142857142857
      min: 32
      std: 11.655323283657165
    total: 28
