normal:
  female:
    age_stats:
      max: 30
      mean: 23.75
      min: 21
      std: 4.193248541803041
    total: 4
  male:
    age_stats:
      max: 32
      mean: 32
      min: 32
      std: null
    total: 100
pathological:
  female:
    age_stats:
      max: 67
      mean: 26.285714285714285
      min: 24
      std: 7.634508123364221
    total: 77
  male:
    age_stats:
      max: 70
      mean: 23.035714285714285
      min: 20
      std: 11.331640863356228
    total: 28
