services:
  experiment:
    build:
      context: ..
      dockerfile: baselines/Dockerfile
    image: divr-baseline-experiment
    volumes:
      - ./data:/var/divr/baselines/data
      - ./divr_baselines:/var/divr/baselines/divr_baselines
      # Mount storage and cache
      - ../.cache/s3prl:/root/.cache/s3prl/
      - "${RESEARCH_DATA_PATH}:/home/storage"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ipc: host
  test:
    image: divr-baseline-experiment
    volumes:
      - ./data:/var/divr/baselines/data
      - ./divr_baselines:/var/divr/baselines/divr_baselines
      # Mount storage and cache
      - ../.cache/s3prl:/root/.cache/s3prl/
      - "${RESEARCH_DATA_PATH}:/home/storage"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ipc: host
    entrypoint: 
      - pipenv
      - run
      - python
      - -m
      - divr_baselines
      - test