services:
  experiment:
    build: .
    image: divr-baselines-experiment:v1
    volumes:
      - ../baselines/data:/var/divr/baselines/data
      - ../baselines/divr_baselines:/var/divr/baselines/divr_baselines
      # Mount storage and cache
      - ../.cache/s3prl:/root/.cache/s3prl/
      - "${RESEARCH_DATA_PATH}:/home/storage"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
